version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./:/ryo226.portfolio
      - /ryo226.portfolio/node_modules
    command: sh -c "yarn && yarn start"
    tty: true
    ports:
      - 3000:3000